#! /usr/bin/env node

var fs = require('fs'),
    path = require('path'),
    Twit = require('twit'),
    TwitterBot = require('node-twitterbot').TwitterBot,
    config = require(path.join(__dirname, 'config.js'));
    https = require('https');

function getImage(url, callback) {
    https.get(url, res => {
        // Initialise an array
        const bufs = [];

        // Add the data to the buffer collection
        res.on('data', function (chunk) {
            bufs.push(chunk)
        });

        // This signifies the end of a request
        res.on('end', function () {
            // We can join all of the 'chunks' of the image together
            const data = Buffer.concat(bufs);

            // Then we can call our callback.
            return callback(null, data.toString('base64'));
        });
    })
    // Inform the callback of the error.
    .on('error', callback);
}

/*var T = new TwitterBot({
 consumer_key: process.env.BOT_CONSUMER_KEY,
 consumer_secret: process.env.BOT_CONSUMER_SECRET,
 access_token: process.env.BOT_ACCESS_TOKEN,
 access_token_secret: process.env.BOT_ACCESS_TOKEN_SECRET
});*/

var T = new Twit(config);

/* T.post('statuses/update', {status: 'Look I am tweeting!'}, function(err, data, response) {
  console.log(data)
}); */

function random_from_array(images){
  return images[Math.floor(Math.random() * images.length)];
}

function upload_random_image(images){
  console.log('Opening an image...');
  var image_path = path.join(__dirname, '/images/' + random_from_array(images)),
    b64content2 = fs.readFileSync(image_path, { encoding: 'base64' });
    // console.log("b64content2")
    // console.log(b64content2)
    picUrl = random_from_array([
      'https://i.ibb.co/v44jwpd/Dz-Hpch-DV4-AMAe3-U.jpg',
      'https://i.ibb.co/J5Xr7rQ/Dz-G62o-DUYAANuoa.jpg',
      'https://i.ibb.co/dDBknMk/Dzg-bx-NVYAADZK9.jpg',
      'https://i.ibb.co/b2YB9jv/Dzzkz-OMVs-AATUyt.jpg',
      'https://i.ibb.co/3MKfDnV/Dz-Wjl-Rl-UUAA4-UTB.jpg',
      'https://i.ibb.co/ctsx2cn/Dz-W9-XHc-Vs-AESF34.jpg',
      'https://i.ibb.co/Xkh30hk/Dzw2-JAw-UUAA9-L-b.jpg',
      'https://i.ibb.co/HzgQ56g/Dzv-PFgj-UUAEJpnf.jpg',
      'https://i.ibb.co/rp0FDZH/Dz-Ux-PQXUYAE00-Rd.jpg',
      'https://i.ibb.co/xCQJS8D/Dz-Rw-Mw-YVYAAh-GG1.jpg',
      'https://i.ibb.co/cv5R1nQ/Dzrveh-GUw-AAr-i6.jpg',
      'https://i.ibb.co/prYMzf0/Dzpmp87-Uc-AAk-U8-O.jpg',
      'https://i.ibb.co/w0cc71M/Dz-Ml-Bmf-U8-AE4-Oht.jpg',
      'https://i.ibb.co/v44jwpd/Dz-Hpch-DV4-AMAe3-U.jpg',
      'https://i.ibb.co/J5Xr7rQ/Dz-G62o-DUYAANuoa.jpg',
      'https://i.ibb.co/dDBknMk/Dzg-bx-NVYAADZK9.jpg',
      'https://i.ibb.co/TH09ZDg/Dzfp-M1f-VYAAz-Tcf.jpg',
      'https://i.ibb.co/cJwGD0m/Dzf-Gpkh-UUAAA8va.jpg',
      'https://i.ibb.co/xMnjz5n/Dzb-Rg-Ls-Uc-AAzxdv.jpg',
      'https://i.ibb.co/j6jNP6m/Dz17xzu-Uc-AA-jwl.jpg',
      'https://i.ibb.co/nMgBzDV/Dz7-W32g-U0-AAGJPM.jpg',
      'https://i.ibb.co/rwc2bzV/Dy-Xwho-UVAAI34bf.jpg',
      'https://i.ibb.co/HGJQLj8/Dy-UAKKWUYAAa-Pc.jpg',
      'https://i.ibb.co/C6rpn1L/Dytzp-BTVs-AAd-Sx-Q.jpg',
      'https://i.ibb.co/tQpVJvQ/Dyt08-FU8-AAQL6-E.jpg',
      'https://i.ibb.co/qsddVJ4/Dyome-ETVAAAyl-Pj.jpg',
      'https://i.ibb.co/HqBxQCW/Dy-O0-ESTU0-AMMy-Cx.jpg',
      'https://i.ibb.co/306YjSy/Dyjs-CHl-VAAAClkn.jpg',
      'https://i.ibb.co/rc2GFY7/Dy-IGx6-FUw-AAD8-AZ.jpg',
      'https://i.ibb.co/HPGfYcx/Dy-AHNVOU0-AEem-GQ.jpg',
      'https://i.ibb.co/0sj94QG/Dy9-WW4-PUc-AAXtz-Y.jpg',
      'https://i.ibb.co/LrkKSJM/Dy4d5-Db-V4-AEQm-FS.jpg',
      'https://i.ibb.co/RDyPPr3/Dy2m-CNUUUAEmto-M.jpg',
      'https://i.ibb.co/9N6S1Fh/Dxz-BGh-VYAAX-0-Q.jpg',
      'https://i.ibb.co/MpC3Ysk/Dxloi4-CUw-AAFu2-C.jpg',
      'https://i.ibb.co/h1bTqzn/Dx-Gb6-My-VAAA6-Eb1.jpg',
      'https://i.ibb.co/qjr4F8r/Dxf-DLk-HVYAA-j-Mb.jpg',
      'https://i.ibb.co/xSf06G5/Dx-ABxxy-Xg-AAx-GEW.jpg',
      'https://i.ibb.co/1f1hz0H/Dx9z-Eg-JUc-AEJs-V8.jpg',
      'https://i.ibb.co/gZfVMM6/Dx6mxn-HUc-AAUw-PS.jpg',
      'https://i.ibb.co/t29Qdh3/Dx0o-Hc-PU0-AEa68b.jpg',
      'https://i.ibb.co/0GBKyWr/Dw-Y2-Xuo-Uw-AIBy-L4.jpg',
      'https://i.ibb.co/dtxPpnM/Dw-TMK-y-Uw-AA4h3-R.jpg',
      'https://i.ibb.co/NsLrYQ3/Dwrdfm2-V4-AAaxiv.jpg',
      'https://i.ibb.co/D75vmjy/Dwip8-TKU0-AAI1i5.jpg',
      'https://i.ibb.co/KbHTNyK/Dw8g-Wx-ZUYAADbke.jpg',
      'https://i.ibb.co/LQkK7rk/D17-R2jd-U8-AAy-Ye-A.jpg',
      'https://i.ibb.co/JjwTQfM/D10-r-EFUk-AELk-Rk.jpg',
      'https://i.ibb.co/KDpFcpr/D2-A8-TIUUc-AAB8-VY.jpg',
      'https://i.ibb.co/TWbqg1k/D1sj8-UCVAAI5-UEj.jpg',
      'https://i.ibb.co/G50pRfQ/D1n-YITp-V4-AA8-By-B.jpg',
      'https://i.ibb.co/nbQHGLW/D1-Nosb9-VAAAi-OBd.jpg',
      'https://i.ibb.co/BNxbnjD/D1hu-CKCU8-AAutx8.jpg',
      'https://i.ibb.co/G3hWpJj/D0y-TRNz-VAAAKS6t.jpg',
      'https://i.ibb.co/R7n5XZj/D0-VICU4-U8-AAd-MMa.jpg',
      'https://i.ibb.co/2c7jPxh/D0u2iv-NUYAAREF1.jpg',
      'https://i.ibb.co/tBRD0sv/D0pl-Rd-V4-AEt-B7-F.jpg',
      'https://i.ibb.co/2KKGXDW/D0m9i-A1-VYAAt-S-s.jpg',
      'https://i.ibb.co/yg93028/D0k-UWCz-VAAA8-P9-I.jpg',
      'https://i.ibb.co/mF913WJ/D0-Kbmpf-V4-AAEu-Vu.jpg',
      'https://i.ibb.co/Zx149vs/D0ibt1d-U8-AAWEfn.jpg',
      'https://i.ibb.co/xL9ZwJy/D0-FRa-D8-UUAELEWe.jpg',
      'https://i.ibb.co/7nfNDsH/D0e8p-YCUc-AED86-G.jpg',
      'https://i.ibb.co/qDq7MPb/D0a-E9vt-UYAA51dc.jpg',
      'https://i.ibb.co/wwTGhLs/D0-Act0u-U8-AAsgn-U.jpg',
      'https://i.ibb.co/z6P6tV6/D0-Qmgs-UYAAW2q-Z.jpg',
      'https://i.ibb.co/jRw6SXv/D2-WI-yh-Uc-AA5uk-W.jpg',
      'https://i.ibb.co/LrTHFdK/D2-Vbq-Pv-Uw-AAct1-C.jpg',
      'https://i.ibb.co/TtmK00b/D2v1-N6-ZU8-AAwidd-1.jpg',
      'https://i.ibb.co/hBhqfvz/D2u-BGGDU8-AEAX2-F.jpg',
      'https://i.ibb.co/wBDWmF4/D2q-Uc-A5-VAAAOh-Hf.jpg',
      'https://i.ibb.co/N6Yvm8n/D2-GMw-SQUk-AEs0n8.jpg',
      'https://i.ibb.co/28pdNyV/D2ge-RYUYAAf-LPB.jpg',
      'https://i.ibb.co/XSrW1hg/D25m-1-KU8-AAcnzb.jpg',
      'https://i.ibb.co/LNNyvcZ/D23n-V53-VYAEp3-Ce.jpg',
      'https://i.ibb.co/Drtcvnj/D3-Gip-Ic-Xg-AEFY7l.jpg',
      'https://i.ibb.co/NrDtLd2/D3-Bz-T0-MVAAER6u-M.jpg',
      'https://i.ibb.co/GWQxK99/D2z-JGLq-UYAALcc-Q.jpg',
      'https://i.ibb.co/TtmK00b/D2v1-N6-ZU8-AAwidd-1.jpg',
      'https://i.ibb.co/rxtR1zN/TE06x-Yodjh8-V-8-I.jpg',
      'https://i.ibb.co/pzPtZqt/Zbc1-B-RDmbq-Vjo0-V.jpg',
      'https://i.ibb.co/pvbsHGf/w-QQVzjrebv-CHZP9w.jpg',
      'https://i.ibb.co/TwrJcHM/vd-PRLprr-M6fw-Etft.jpg',
      'https://i.ibb.co/4s9QhsW/SJ4-H-p-Uh8s-o-Hs92.jpg',
      'https://i.ibb.co/j3RqsTh/QBp7-I-Hu-EI-POg-T.jpg',
      'https://i.ibb.co/t4TmQf5/Q8-Lz7ybl3-NKy3-26.jpg',
      'https://i.ibb.co/1JtmJbJ/I6z-Lo-T1-RQb-J2-BU8-O.jpg',
      'https://i.ibb.co/TRknF72/I1w2-Txpc-Jy-A-c8-PA.jpg',
      'https://i.ibb.co/0cbvSD4/H9k-Bj-Q0-BCASE9-E-s.jpg',
      'https://i.ibb.co/6FwPZg7/D5t5wz-AUYAEVr-E0.jpg',
      'https://i.ibb.co/pbTKGPh/D5c-Zuo-Xo-AMDgtk.jpg',
      'https://i.ibb.co/DwGbg8V/D59-MWKd-U0-AEka-St.jpg',
      'https://i.ibb.co/9Y4PYBK/D57t-0-WV4-AA-C-F.jpg',
      'https://i.ibb.co/KyRHqwf/D54-Ox-AGVUAAfhvm.jpg',
      'https://i.ibb.co/ZShhgwb/D52h-Rs8-U8-AACjy-W.jpg',
      'https://i.ibb.co/fS05Spk/D5zfc-H1-V4-AAHNHU.jpg',
      'https://i.ibb.co/9tFqMzB/D5sq-Qe-LV4-AAm-VTU.jpg',
      'https://i.ibb.co/tP12LD3/D5-NFHek-Uc-AEckd2.jpg',
      'https://i.ibb.co/1q6yTmw/9hg-Yoo-WVNo1z-Sa1-Y.jpg',
      'https://i.ibb.co/Hr9B0kL/Screen-Shot-2019-07-31-at-2-28-29-PM.png',
      'https://i.ibb.co/myJ8hc5/Screen-Shot-2019-07-31-at-2-28-38-PM.png',
      'https://i.ibb.co/441B7RC/Screen-Shot-2019-07-31-at-2-28-43-PM.png',
      'https://i.ibb.co/6shTq65/Screen-Shot-2019-07-31-at-2-28-52-PM.png',
      'https://i.ibb.co/nczyQt6/Screen-Shot-2019-07-31-at-2-29-01-PM.png',
      'https://i.ibb.co/Z8cNnFp/Screen-Shot-2019-07-31-at-2-29-08-PM.png',
      'https://i.ibb.co/09t4TgH/Screen-Shot-2019-07-31-at-2-29-17-PM.png',
      'https://i.ibb.co/dWTnLQq/Screen-Shot-2019-07-31-at-2-29-21-PM.png',
      'https://i.ibb.co/bzTxt4s/Screen-Shot-2019-07-31-at-2-29-27-PM.png',
      'https://i.ibb.co/3RbsMRV/Screen-Shot-2019-07-31-at-2-29-35-PM.png',
      'https://i.ibb.co/F5HnXQv/Screen-Shot-2019-07-31-at-2-29-39-PM.png',
      'https://i.ibb.co/MD5LJ3J/Screen-Shot-2019-07-31-at-2-29-47-PM.png',
      'https://i.ibb.co/3dLy105/Screen-Shot-2019-07-31-at-2-29-51-PM.png',
      'https://i.ibb.co/DwkS4G3/Screen-Shot-2019-07-31-at-2-29-57-PM.png',
      'https://i.ibb.co/XCSQ2sT/Screen-Shot-2019-07-31-at-2-30-02-PM.png',
      'https://i.ibb.co/3kCgm14/Screen-Shot-2019-07-31-at-2-30-07-PM.png',
      'https://i.ibb.co/sKR6RP0/Screen-Shot-2019-07-31-at-2-30-14-PM.png',
      'https://i.ibb.co/BzrzTCK/Screen-Shot-2019-07-31-at-2-30-22-PM.png',
      'https://i.ibb.co/P1nBWbf/Screen-Shot-2019-07-31-at-2-30-27-PM.png',
      'https://i.ibb.co/d07F2Nr/Screen-Shot-2019-07-31-at-2-30-32-PM.png',
      'https://i.ibb.co/H4fZjMm/Screen-Shot-2019-07-31-at-2-30-36-PM.png',
      'https://i.ibb.co/smyTNmK/Screen-Shot-2019-07-31-at-2-30-44-PM.png',
      'https://i.ibb.co/FxV2Gv7/Screen-Shot-2019-07-31-at-2-30-50-PM.png',
      'https://i.ibb.co/kQB154m/zvzz0-capybaras-love-spa-days-lg.jpg',
      'https://i.ibb.co/GQD2kVJ/Zoo.jpg',
      'https://i.ibb.co/dJmbLmC/zoo-711050-1280.jpg',
      'https://i.ibb.co/vVLsGw7/Yellow-headed-caracara-28-Milvago-chimachima29-on-capybara-28-Hydrochoeris-hydrochaeris29-JPG.jpg',
      'https://i.ibb.co/CsVL6LY/ya.jpg',
      'https://i.ibb.co/sqwX14y/XwLk6M7.png',
      'https://i.ibb.co/JxmPH4p/wn-40-hinase-yawning-01-october-2017-063.jpg',
      'https://i.ibb.co/f1bMTwM/wn-20-injured-aoba-28-jun-2018-100.jpg',
      'https://i.ibb.co/zsCptHf/wired-the-capybara-may-be-chill-but-it-still-says-no-to-drugs.jpg',
      'https://i.ibb.co/ZfQnzW7/willow-2.jpg',
      'https://i.ibb.co/QmyZbWd/wildlife-capybara-swim.jpg',
      'https://i.ibb.co/k2LsqWk/wellington-zoo-capybaras-lead-637x397.png',
      'https://i.ibb.co/YXCX7sW/web1-star-capybara-042015db-004-3.jpg',
      'https://i.ibb.co/Xj7rQG0/water-pigs-3557854-340.jpg',
      'https://i.ibb.co/HBgKNDd/Wasserschwein-Least-Concern-525x330.jpg',
      'https://i.ibb.co/19QQ3Xb/vp-capybara-shutterstock-461068126.jpg',
      'https://i.ibb.co/5jSCshK/tumblr-p3cfpi-Y8ip1sutuwgo1-1280.jpg',
      'https://i.ibb.co/nQpCs8H/tumblr-mo03cphug31sutuwgo1-1280.png',
      'https://i.ibb.co/mXmfYQb/thumbcapybara1844-498.jpg',
      'https://i.ibb.co/Y06pFNd/thumb-1-6530-6540-Wasserschweine-capybara-water-pig-kosen-koesen-germany-Display-Prop-Decor-Luxury-Fine-Studio-Handmade-Stuffed-Lifesize-Lifelike-Realistic-Large-Plush-Animal.jpg',
      'https://i.ibb.co/mqr6h4q/the-capybara-as-a-pet-399-600.jpg',
      'https://i.ibb.co/bQLxLSZ/tgHsVXM.jpg',
      'https://i.ibb.co/CbjkRdp/TELEMMGLPICT000149129435-trans-Nv-BQz-QNjv4-Bq-J6-Ri-S5-Rjb-N6p5-OO4zvskj4n-PAkv-g-Oe-YV-Bl-Ojqs-Hg.jpg',
      'https://i.ibb.co/MSY33gy/Sweetie-t1000.jpg',
      'https://i.ibb.co/2Kk5FTR/stock-photo-animal-nature-wildlife-mammal-isolated-capybara-5d09a942-e888-4b1c-a4ae-d08642b3d2f4.jpg',
      'https://i.ibb.co/RySmxkc/source.gif',
      'https://i.ibb.co/4VFjzmx/so-a-dog-and-capybara-walk-into-a-room.jpg',
      'https://i.ibb.co/DQN3bmn/SIA0023.jpg',
      'https://i.ibb.co/tmcS03P/shutterstock-608351948.jpg',
      'https://i.ibb.co/Tw5TTbR/sfds.jpg',
      'https://i.ibb.co/6gqmtZ2/second-capybara-found-case-closed.png',
      'https://i.ibb.co/2ZG3Tmv/Screen-Shot-2016-04-15-at-12-26-34-PM.png',
      'https://i.ibb.co/qdQtsK1/SBZoo-Capybara3.jpg',
      'https://i.ibb.co/bmPxP98/SB-Zoo-Capybara-2-e1559851811719.jpg',
      'https://i.ibb.co/6FwsSfx/s-top-TEMP425x425-1002.jpg',
      'https://i.ibb.co/WxY02mK/RY7-UH-vb-400x400.jpg',
      'https://i.ibb.co/pXP2jJX/RS16551-IMG-4753-scr.jpg',
      'https://i.ibb.co/qYmnDvw/rr-composite-capybara.jpg',
      'https://i.ibb.co/MCWB77v/rio-de-janeiro-capybara-watching.jpg',
      'https://i.ibb.co/8dZVX2f/rio-de-janeiro-brazil-august-08-a-capybara-crosses-a-fairway-during-a-practice-round-during-day.jpg',
      'https://i.ibb.co/2gY4snC/r0-0-5568-3712-w1200-h678-fmax.jpg',
      'https://i.ibb.co/Hnwr7W9/pincapybara.png',
      'https://i.ibb.co/MCKKYx1/p-Evp-Hv-YU-720.jpg',
      'https://i.ibb.co/479LVVR/pettingcapybara01.jpg',
      'https://i.ibb.co/85J4Mrz/page-0.jpg',
      'https://i.ibb.co/2540zsk/p049jkzx.jpg',
      'https://i.ibb.co/3McGg2J/original.jpg',
      'https://i.ibb.co/TPh11X1/o-CHEESECAKE-CAPYBARA-PUPPIES-5700.jpg',
      'https://i.ibb.co/0GqdMsQ/o-CHEESECAKE-CAPYBARA-PUPPIES-570.jpg',
      'https://i.ibb.co/S7nHWn0/nm-04capyh-32030672-u171.jpg',
      'https://i.ibb.co/7WgyWPV/nintchdbpict000019101072.jpg',
      'https://i.ibb.co/dfxM0pZ/news-twin-capybara-02.jpg',
      'https://i.ibb.co/MGWvkMp/News-PGHZoo-AP-WEB.jpg',
      'https://i.ibb.co/DYYYrM7/mp840x830mattef8f8f8t-pad750x1000f8f8f8.jpg',
      'https://i.ibb.co/2SP07Yw/Monkeys-ride-capybara-10102012-jpg-114738.jpg',
      'https://i.ibb.co/hHmzqZk/mn1-000460.jpg',
      'https://i.ibb.co/pnLqs92/mellow-details-about-the-chillest-dude-bro-animal-the-capybara-x-gifs-2-3.jpg',
      'https://i.ibb.co/7NPfmsS/medium.jpg',
      'https://i.ibb.co/m4PHHRM/MCT-inside-banner-mobile.jpg',
      'https://i.ibb.co/JRVYmBk/MCT-inside-banner-desktop.jpg',
      'https://i.ibb.co/6RBN1mH/MCT-1.jpg',
      'https://i.ibb.co/mvxyRVJ/maxresdefault3.jpg',
      'https://i.ibb.co/d5b676w/maxresdefault2.jpg',
      'https://i.ibb.co/z4PZTmZ/maxresdefault1.jpg',
      'https://i.ibb.co/CsWxDYs/maxresdefault0.jpg',
      'https://i.ibb.co/mH6R7gt/maxresdefault.jpg',
      'https://i.ibb.co/vVb1hJn/main-9001.jpg',
      'https://i.ibb.co/9gzGthj/main-9000.jpg',
      'https://i.ibb.co/4mdGTjf/main-900.jpg',
      'https://i.ibb.co/F4DvW0j/macaroni-25-crop-19-sep-2014-107.jpg',
      'https://i.ibb.co/sHNknm0/lifebuzz-19abe20f57326c9b3e05b5561abdec17-limit-2000.jpg',
      'https://i.ibb.co/bbhtRwf/Lesser2-BCapybara2-B2528-Hydrochoerus2-Bisthmius2529.jpg',
      'https://i.ibb.co/pQ9DY3k/Lesser-Capybaras-1-800x530.jpg',
      'https://i.ibb.co/k0zP1BL/kx8qew-b78601688z-120100202165112000grbmav15-1.jpg',
      'https://i.ibb.co/BjkrfcG/kx8qev-b78601688z-120100202165112000grbmav17-1.jpg',
      'https://i.ibb.co/jLJWvMz/kosen-14-capybara-25cm-6540.jpg',
      'https://i.ibb.co/rGd5SML/KKnu-Uabt-1920.jpg',
      'https://i.ibb.co/sg93p1s/katja-capybara-3-klaus-seehawer-800x533.jpg',
      'https://i.ibb.co/BLvxwFP/kapibara-1170-483-8191369695.png',
      'https://i.ibb.co/TKSHF99/jojo-capybara-and-his-dog-friends.jpg',
      'https://i.ibb.co/72QRmtZ/Joe-Joe-the-Capybara-looks-after-baby-chicks.jpg',
      'https://i.ibb.co/HdLB9zb/i-Stock-000002460899-XSmall.jpg',
      'https://i.ibb.co/VqBmTV0/i-Stock-000001572797-XSmall.jpg',
      'https://i.ibb.co/n7N5NhM/IMG-420920nursing.jpg',
      'https://i.ibb.co/G3pKKN7/IMG-0950-1140x580.jpg',
      'https://i.ibb.co/BcsNbsc/hydrochoerus-hydrochaeris-a005-p3-0.jpg',
      'https://i.ibb.co/xXx1dXR/hydrochoerus-hydrochaeris-a005-p2-0.jpg',
      'https://i.ibb.co/R6sRsPG/hydrochaeris-hydrochaeris.jpg',
      'https://i.ibb.co/JpcM4cp/http3-A2-F2-Fo-aolcdn-com2-Fhss2-Fstorage2-Fmidas2-Ffe9404f1ebb1d1eeccea1bf2577b56012-F2036263162-FScreen2-BShot2-B2016-03-312-Bat2-B3-40-522-BPM.jpg',
      'https://i.ibb.co/c87vGKR/high-park-zoo-slider-2-1024x533.jpg',
      'https://i.ibb.co/9hHYVJ6/hero-capybara.jpg',
      'https://i.ibb.co/bFYRzQX/hayley-03-bh31-3-06-crw-0334-01.jpg',
      'https://i.ibb.co/g760Vwr/GWcUT57.jpg',
      'https://i.ibb.co/0QQDP6X/gr0626-capybarasjpg-15e08daf20da2175-large.jpg',
      'https://i.ibb.co/LY6FhNm/giphy.gif',
      'https://i.ibb.co/F3VpmyC/gettyimages-587336310.jpg',
      'https://i.ibb.co/ts0PR7N/Getty-Images-460739682.jpg',
      'https://i.ibb.co/f0zFRFD/fb0.jpg',
      'https://i.ibb.co/K5McyKn/f76129acdd58402b926c30d8cfe7da77.jpg',
      'https://i.ibb.co/0Kq6wfh/elem-worlds-largest-rodent-923d0afd.jpg',
      'https://i.ibb.co/h8zjHkD/DZG-capybara2-1200x604.jpg',
      'https://i.ibb.co/rMbTc0Z/DXd1-TH7-IPs4ph-RZZYQIBA5-UQ2-D7-EMd-Zx-Fnn-BBZ9b-WBo.jpg',
      'https://i.ibb.co/b3xhdSv/DUgm-Or-UUQAAOR-J.jpg',
      'https://i.ibb.co/jLb7yWG/cute-capybara-lying-farm-with-baby-animal-mother-s-day-concept-32485-346.jpg',
      'https://i.ibb.co/r6Gg65q/csm-Wasserschweine-Kuscheln-ist-angesagt-270913-Kopie-b192ea23a3.jpg',
      'https://i.ibb.co/hKwTFCj/csm-Wasserschwein-Hellabrunn-Daniela-Hierl-e61466b83b.jpg',
      'https://i.ibb.co/LtK2gJD/csm-Wasserschwein-Hellabrunn-2016-Eva-Korb-44b331af43.jpg',
      'https://i.ibb.co/zfhB58t/courtesey-of-grant-lampard.jpg',
      'https://i.ibb.co/Ch5KJQd/colombia-5964.jpg',
      'https://i.ibb.co/rpBkp4n/cheesecake-the-capybara-fosters.jpg',
      'https://i.ibb.co/KyPWtwS/characteristics-of-capybaras-399-0-600.jpg',
      'https://i.ibb.co/9NrrbBj/capys.jpg',
      'https://i.ibb.co/Xbdkx8Z/capypic.jpg',
      'https://i.ibb.co/93fG5CV/capybarasmall.jpg',
      'https://i.ibb.co/gTP9Lhs/Capybara-Slider.jpg',
      'https://i.ibb.co/Jxnwgmb/capybaras1.jpg',
      'https://i.ibb.co/FsZjmFx/Capybaras.jpg',
      'https://i.ibb.co/7pNQbLK/Capybaras-Swimming.jpg',
      'https://i.ibb.co/gRMx6Rz/Capybara-LR-18-min20crop.jpg',
      'https://i.ibb.co/ryt3LLt/capybara15.jpg',
      'https://i.ibb.co/0sZ7SpB/capybara14.jpg',
      'https://i.ibb.co/1JfGK3r/capybara12.jpg',
      'https://i.ibb.co/26Gzk3v/capybara11.jpg',
      'https://i.ibb.co/qN575DB/capybara10.jpg',
      'https://i.ibb.co/mbn6Fsc/capybara7.jpg',
      'https://i.ibb.co/g9kvmxv/capybara6.jpg',
      'https://i.ibb.co/F85gCLY/capybara5.jpg',
      'https://i.ibb.co/vctLywh/capybara3.jpg',
      'https://i.ibb.co/Rz055C7/Capybara2-Slider.jpg',
      'https://i.ibb.co/pyWNZgn/capybara02.jpg',
      'https://i.ibb.co/thF1yvD/capybara2.jpg',
      'https://i.ibb.co/R7Y7Sf4/capybara1.jpg',
      'https://i.ibb.co/qj7YHHG/Capybara-with-Given.png',
      'https://i.ibb.co/stQTmF6/capybara-unusual-animal-friendship-fb-700-png.jpg',
      'https://i.ibb.co/4F2TSYZ/capybara-onsen-bath-cute-kawaii-animals-japan-japanese-hot-spring-onsen-bathing-competition-showdown.png',
      'https://i.ibb.co/jMd6B0P/capybara-on-head-3.jpg',
      'https://i.ibb.co/1sxKf8J/Capybara-Olympics.jpg',
      'https://i.ibb.co/D8jS9Jd/capybara-library.jpg',
      'https://i.ibb.co/rdHfgXC/capybara-kiss.jpg',
      'https://i.ibb.co/JQv5YQM/Capybara-IMG-9864-RJPG.jpg',
      'https://i.ibb.co/WsMSXRk/Capybara-IMG-5022-RJPG.jpg',
      'https://i.ibb.co/NKtPNfr/Capybara-Images.jpg',
      'https://i.ibb.co/z5vgVJV/Capybara-Hydrochoerus-hydrochaeris-1.jpg',
      'https://i.ibb.co/sFwrhjb/capybara-hot-springs-japan-3.jpg',
      'https://i.ibb.co/smJbg8p/capybara-hero-5.jpg',
      'https://i.ibb.co/CMKzysq/capybara-hero-3.jpg',
      'https://i.ibb.co/44Kgpf8/capybara-hero-1.jpg',
      'https://i.ibb.co/T0Z1Dq1/capybara-Hemera-100328664.jpg',
      'https://i.ibb.co/4VJ8Vpd/capybara-hat.jpg',
      'https://i.ibb.co/M6NG847/Capybara-hangs-out-with-pair-of-Border-Collies.jpg',
      'https://i.ibb.co/JHw2JMd/capybara-group.jpg',
      'https://i.ibb.co/XtCtTt0/capybara-gets-some-scritches-31926539.png',
      'https://i.ibb.co/dBsDXFY/capybara-gallery-3.jpg',
      'https://i.ibb.co/qsTJ53Q/capybara-gallery-2.jpg',
      'https://i.ibb.co/K5rs6HP/Capybara-featured.jpg',
      'https://i.ibb.co/H7ywFZ5/capybara-feature.jpg',
      'https://i.ibb.co/S3QYbM8/Capybara-Family.jpg',
      'https://i.ibb.co/rdqn6Ch/capybara-en-escape01.jpg',
      'https://i.ibb.co/J3ZSqKv/CAPYBARA-ED-2.jpg',
      'https://i.ibb.co/fHYVq9c/capybara-eating-jpg-838x0-q80.jpg',
      'https://i.ibb.co/fk5CknP/capybara-eating.jpg',
      'https://i.ibb.co/q9HYRMh/capybara-e1427917983725.jpg',
      'https://i.ibb.co/ZxQPL2H/capybara-definitely-the-biggest-and-possibly-the-cutest-rodent-12-pictures-12.jpg',
      'https://i.ibb.co/3yHQRsJ/capybara-bird-246671.jpg',
      'https://i.ibb.co/7v3b08Q/capybara-basic-w-ip.jpg',
      'https://i.ibb.co/KxW6gvw/capybara-banner.jpg',
      'https://i.ibb.co/fqrr38n/Capybara-Baby.jpg',
      'https://i.ibb.co/t4SRsYk/capybara-4357401-340.jpg',
      'https://i.ibb.co/NjFzdKR/capybara-678x381.jpg',
      'https://i.ibb.co/Qmkfqcf/capybara-600.jpg',
      'https://i.ibb.co/qg773Yz/capybara-13-545x363.jpg',
      'https://i.ibb.co/zPjSvLC/capybara-10.jpg',
      'https://i.ibb.co/YWpKqhm/Capybara-4-650x425.jpg',
      'https://i.ibb.co/23zkPKd/capybara-3.jpg',
      'https://i.ibb.co/vD1W5SS/Capybara-3-650x425.jpg',
      'https://i.ibb.co/74DHFNq/capybara-2.jpg',
      'https://i.ibb.co/vkYP0qh/Capybara-0002-5761-1280x720.jpg',
      'https://i.ibb.co/Xthy0DM/capybara-2-2-1.jpg',
      'https://i.ibb.co/BV3Mdgn/capybara-1.jpg',
      'https://i.ibb.co/cbpyR6j/capybara-splash.jpg',
      'https://i.ibb.co/XFsV3Jq/capybara-sitting-sideways-18114724916.jpg',
      'https://i.ibb.co/Hgsg6YY/Capybara-Pepe.jpg',
      'https://i.ibb.co/vjRxhhj/capybara-nationalgeographic-1518115.jpg',
      'https://i.ibb.co/R9PYLPG/Capybara-harness.jpg',
      'https://i.ibb.co/yXLntNk/Capybara-Fur-And-Feathers-ZN.jpg',
      'https://i.ibb.co/48C2ZJY/Capybara-baby-bottle2.jpg',
      'https://i.ibb.co/K0y38Ls/Capybara-28-Hydrochoerus-hydrochaeris29-JPG.jpg',
      'https://i.ibb.co/QFnc79x/capy4.jpg',
      'https://i.ibb.co/23q9BpS/capy.jpg',
      'https://i.ibb.co/9y6VzPY/capy-think.jpg',
      'https://i.ibb.co/pPh5KV5/capy-both.jpg',
      'https://i.ibb.co/zF9yh7L/capy-1280x720.jpg',
      'https://i.ibb.co/qrQrdqM/capy-619-386.jpg',
      'https://i.ibb.co/yS2wP8G/Capy-2.gif',
      'https://i.ibb.co/fYyqfXv/capivara-imagem.jpg',
      'https://i.ibb.co/fqwxwGX/capibara.jpg',
      'https://i.ibb.co/r69CrSr/capibara.jpg',
      'https://i.ibb.co/D8YWnjr/Can-you-have-a-Capybara-as-a-Pet.jpg',
      'https://i.ibb.co/Tm07ddm/c4f2fd673d78410ae2b3cb7e45f4d8e9.jpg',
      'https://i.ibb.co/74v51m2/brevard-zoo-calypso-rainforest-resident-580.jpg',
      'https://i.ibb.co/dGTxf0S/brazil-a-capybara-with-its-young-ralph-h-bendjebar.jpg',
      'https://i.ibb.co/LYcw04g/baby-capy-2.jpg',
      'https://i.ibb.co/vkXR8vt/Babies-Small-Rodents-Cute-Fur-Capybara-Animals-4207870.jpg',
      'https://i.ibb.co/dDM89K6/B9720247716-Z-1-20190712152839-0002-BG4-NE26-URP-1-0.jpg',
      'https://i.ibb.co/3f1fYH0/ap-switzerland-zoo-16835655.jpg',
      'https://i.ibb.co/9q0kL9q/animals-hero-capybara.jpg',
      'https://i.ibb.co/WD958My/a1920x1080-Coverphotocappy2.jpg',
      'https://i.ibb.co/jg53t6s/a9c2213d2df0b526bf0f7fecd3dca3fa.jpg',
      'https://i.ibb.co/bKvTLd6/a-capybara-mother-and-her-young-walk-inv-1.jpg',
      'https://i.ibb.co/NnNJ0h3/636054269638393253-JT2-3230-JPG.jpg',
      'https://i.ibb.co/VgmQ686/4203153200000578-4663910-image-a-24-1499155635583.jpg',
      'https://i.ibb.co/6wn2J5P/20111223121147.jpg',
      'https://i.ibb.co/FBdSWvC/2226196965001-4913140637001-4913137806001-vs.jpg',
      'https://i.ibb.co/mRDCTNh/1540872522304.jpg',
      'https://i.ibb.co/yhw649P/1493831080999-shutterstock-562102384.jpg',
      'https://i.ibb.co/GP2SPjB/38613782764-ce5f7b6fb0-b.jpg',
      'https://i.ibb.co/dLvsWkC/3658863090-6d8100ea2f.jpg',
      'https://i.ibb.co/FJCypt1/3284252557-036d79666a-o.jpg',
      'https://i.ibb.co/HVcvCbT/1049688427.jpg',
      'https://i.ibb.co/dMjWrL8/87740830-XS.jpg',
      'https://i.ibb.co/TYyZDcF/87701675-XS.jpg',
      'https://i.ibb.co/FsB1SGd/40008530-2136206926451154-3347821037503905792-n.jpg',
      'https://i.ibb.co/x5JRSwy/9686424-6692719-image-a-24-1549917231173.jpg',
      'https://i.ibb.co/CK1xwHd/9175403-orig.jpg',
      'https://i.ibb.co/qmTpJhC/8387034-f520.jpg',
      'https://i.ibb.co/vBjLWPc/2015252-F02252-F19252-Fd9252-Fcapybarahot-94c18-jpg252-F1200x627.jpg',
      'https://i.ibb.co/Fq6sMCr/081216-WT-capybaras-free.jpg',
      'https://i.ibb.co/CvTz92Q/58504b73d1137-image.jpg',
      'https://i.ibb.co/fHKq4tm/58504b6f3c372-image.jpg',
      'https://i.ibb.co/WxpPSGJ/14553-main.jpg',
      'https://i.ibb.co/9VHztSf/13072.jpg',
      'https://i.ibb.co/VHs3yJN/12216-main.jpg',
      'https://i.ibb.co/98PJVYQ/2018-05-04-new-40648590-I1-JPG.jpg',
      'https://i.ibb.co/FWbsVD0/2016-Capybara-2-in-the-zoo-square.jpg',
      'https://i.ibb.co/MMLwTx8/2012-10-04-17-14-10-w.jpg',
      'https://i.ibb.co/4gPC22S/2012-10-17-02-s-Gari-Piig.jpg',
      'https://i.ibb.co/G3TV78G/1400x84620-HYDHYD202.jpg',
      'https://i.ibb.co/hWBgjmr/1200px-Capybara-Hattiesburg-Zoo-2870909b-4229-2560x1600.jpg',
      'https://i.ibb.co/7SdP9rG/1200-535266233-side-view-of-capybara.jpg',
      'https://i.ibb.co/jvc6wVy/1127-12955.jpg',
      'https://i.ibb.co/SsbKkKk/976-380.jpg',
      'https://i.ibb.co/6gmPmKy/900-467449687-capybara-in-sun-light.jpg',
      'https://i.ibb.co/cvvLRdx/0829-capybara-1000x667.jpg',
      'https://i.ibb.co/2Y8gp9T/800-ko-kingdom92.jpg',
      'https://i.ibb.co/Nx6RHP7/568a774ac4525311f2bb0a73493f3037.jpg',
      'https://i.ibb.co/0MPH9BQ/560fd6b80e4d5-560fd668b1dce-511482178.jpg',
      'https://i.ibb.co/s9p2MM7/552d1c3de4b0026284f3b130-cv1.jpg',
      'https://i.ibb.co/MSz21zL/0526capybara.jpg',
      'https://i.ibb.co/K5PyYqT/393.jpg',
      'https://i.ibb.co/XFP950p/26-capybara-yuzu-w600-h315-2x.jpg',
      'https://i.ibb.co/YQ7sxnr/9.jpg',
      'https://i.ibb.co/q70b4QH/8d4f1c6c152f73594171eda20571be365e5af25a-orig.jpg',
      'https://i.ibb.co/8rRc1N5/7tJ7.gif',
      'https://i.ibb.co/jvTGp6x/5bahgaw84wu01.jpg',
      'https://i.ibb.co/wgtXdrF/3h-BW-Capybara-Family-0622-Super-Portrait.jpg',
      'https://i.ibb.co/0yyq23D/3-CATERS-CAPYBARA-SURROGATE-ANIMAL-FRIENDS-04-800x498.jpg',
      'https://i.ibb.co/VL63nDp/2c71bd9e075179b83b0568904cac9789.jpg',
      'https://i.ibb.co/8YV4bLj/02-07-2014-capybara-monkey.jpg',
      'https://i.ibb.co/fDCxpq4/1-Tik-Co-Iz1q-OJ9iy-FMJ-MBi-Q.jpg',
      'https://i.ibb.co/0tzhFHG/1-Oh-Ii-W-w1u-DP5-Fhgfc-Xv-LQ.jpg',
      'https://i.ibb.co/bm2xtFc/1-L7-Gflcv-THQ2-Gc2g52-Mc-C8-Q.png',
      'https://i.ibb.co/480q1bh/01-Nutmeg-Baby.jpg',
      'https://i.ibb.co/B2KSJrv/0-CATERS-CAPYBARA-SURROGATE-ANIMAL-FRIENDS-01-800x498.jpg',
      'https://i.ibb.co/d0h8sXp/72748973-capybara-6.jpg'
    ])

    b64content = getImage(picUrl, function (err, data) {
      if (err) {
        throw new Error(err);
      }
    //   return data;
    // })
    // console.log("b64content")
    // console.log(b64content)
  // console.log(data)
    console.log('Uploading an image...');

    T.post('media/upload', { media_data: data }, function (err, data, response) {
      if (err){
        console.log('ERROR:');
        console.log(err);
      }
      else{
        console.log('Image uploaded!');
        console.log('Now tweeting it...');

        T.post('statuses/update', {
          /* You can include text with your image as well. */
          // status: 'New picture!',
          /* Or you can pick random text from an array. */
          status: random_from_array([
            'capybaras are actually large rodents',
            'a fully grown capybara reaches 4 feet in length and weight of 140 pounds',
            'female capybaras are larger than males',
            'capybaras are herbivores (eat plants). they graze grass and eat aquatic plants most of the night. they also eat fruit and bark of the tree.',
            'capybaras regurgitate their food and chew it several times',
            'jaguars, anacondas, caimans, harpy eagles hunt and eat capybaras :(',
            'when capybaras sense danger, they produce warning bark which alerts other members of the group',
            'capybaras live in large groups, from 10-30 members',
            'capybaras usually have one litter per year. pregnancy lasts 5-6 months and ends with 4 babies',
            'capybaras live 8-10 years in the wild and up to 12 years in captivity',
            'capybaras need water to keep their dry skin moist and are found only in areas with abundant water sources',
            'capybaras are social creatures',
            'capybaras are most active during dawn or dusk',
            'capybara eat mostly water plants and grasses, though grain, melons and squash can also be on the menu',
            'around a year old, capybara pups leave their parent’s groups to find new ones',
            'the scientific name for a capybara is Hydrochoerus hydrochaeris',
            'capybaras are listed as least concern by the IUCN',
            'capybaras can stay underwater for up to five minutes at a time, according to the San Diego Zoo',
            'the scientific name for capybara comes from Hydro chaeris, which means "water hog" in Greek',
            'an Amazon tribe calls the capybara Kapiyva or "master of the grasses" in their native language',
            'capybaras inhabit southern Central America and northern South America in both savannas and rain forests near ponds, rivers, or lakes',
            'capybaras webbed feet help them maneuver in water and traverse soft, muddy ground',
            'capybaras facial features are located towards the top of their large heads, allowing them see and breathe while swimming',
            'capybaras can press their ears against their heads to keep water out',
            'capybaras have special digestive adaptations that allow them to absorb enough nutrients from their highly fibrous diet',
            'capybaras eat their own droppings – an activity called coprophagy',
            'a typical capybara group includes one dominant male, several females, their offspring, and a few subordinate males',
            'two male capybaras might fight for dominance. they will charge each other, rear up onto their hind legs, and engage in a scuffle until one flees the scene',
            'baby capybaras are not effective swimmers at first, so they stay on land, hiding under brushy cover',
            'capybara populations have been largely affected by hunting in the past',
            'people eat capybara meat and produce leather from their skin',
            'capybaras are closely related to guinea pigs and rock cavies, and more distantly related to chinchillas and agouti',
            'capybaras have reddish to dark brown fur that is long and brittle—perfect for drying out quickly on land',
            'along with the seasons, the presence of predators affects what time of day capybaras are active—which may be day or night, and is often at dawn and dusk',
            'like other rodents, capybaras’ teeth grow continuously, and they wear them down by grazing on aquatic plants, grasses, and other plentiful plants',
            'capybara poo is most protein rich in the morning from the high number of microbes digesting the previous day’s meals',
            'capybaras don’t mind being alone',
            'because their meat can be consumed during lent, capybaras are eaten more before Easter',
            'capybaras are the largest living rodents on Earth.',
            'today, it is prohibited to hunt capybaras in Brazil, while in Venezuela its hunting is regulated',
            'as they are rodents, capybaras have a sharp set of teeth and could potentially be dangerous, but they rarely bite humans',
            'capybaras got their name from the Tupi language from Brazil',
            'capybaras literal translation means “one who eats slender leaves”',
            'like many other rodents, capybaras mostly hop!',
            'other animals love to use the capybara as a chair',
            'capybaras have webbed feet',
            'there are hot springs in Japan that are home to capybaras',
            'japan recently organized a capybara bathing competition',
            'capybara have vestigial tails',
            'capybara feet enable them to wade in the water and keep their balance',
            'the “living chairs” and “nature’s ottoman” are other names used to refer to the capybaras',
            'capybaras are a friendly animal allowing animals to play around it as much as they like',
            'besides their being sociable, the capybaras also have a heavy, barrel-shaped body that enables it to carry other animals',
            'no matter how far away from home they go in search of food, the capybaras always return home',
            'capybaras depend on their excellent sense of smell to trace their steps; a process called scent making',
            'capybaras have two types of scents: the morillo and the anal glands',
            'for males, the anal glands have detachable hairs attached to them',
            'male capybara anal gland hairs have a coating of scent on them released when they come into contact with objects such as plants',
            'as the capybara moves around feeding on varieties of plants, it marks every plant along the way with its scent',
            'to get back home the capybara just follows the smell of its path',
            'capybaras can be sun burned',
            'capybara hair is not enough to cover their whole body which about 1.2 meters long and 0.6 meters wide',
            'capybaras are susceptible to sunburns',
            'in order to protect their skin from the sun’s heat, capybaras seek cover in water or mud',
            'capybaras lack the down hair and ground hair',
            'capybara get on very well with other capybara',
            'capybara have something in common with hippos; their eyes, nostrils and ears are all located at the top of their head meaning that it can learn all it needs to learn about its surroundings whilst keeping most of its body hidden underwater',
            'in the 16th century the capybara was classified as a fish by the Catholic Church so that the meat could be eaten on Fridays and during Lent',
            'capybaras have been known to run as fast as a horse',
            'kids may find this animals nickname "water hog" amusing, but as the name implies, capyabara are found in places where water is plentiful',
            'the capybara often competes with farm animals for food',
            'travel in search of food may take Capybaras far from their homes, but they almost always return to the same exact spot',
            'capybaras are known for making a variety of vocal noises to communicate',
            'capybaras often squeal, whistle, grunt, bark and purr',
            'twilight, early morning and sunset are the most active hours for capybaras',
            'capybaras have a scent gland located on their nose which resembles a bump and they use it to mark their territory',
            'capybaras mate only in the water and the male is always the single dominant male from the group',
            'nurturing mothers will nurse and care for any of the young within the group for the first 16 weeks',
            'once you learn a bit more about these rodents of unusual size it’s hard not to find their super-serious faces and sturdy shapes adorable',
            'capybaras are usually friendly but people who have been bitten by them report their teeth as being sharp',
            'capybaras are amazing swimmers',
            'capybaras can be pets',
            'capybaras kept as pets have been known to mow lawns for extra snacking',
            'capybaras are the life of the party',
            'sometimes as many as a 100 capybaras will gather together',
            'capybaras are social and playful animals.',
            'capybaras are very chatty, they make noise all the time when they’re together, either clicking, whistling or purring',
            'when capybaras want to sound an alarm they bark like dogs',
            'capybaras are the favourite food of anacondas, one of the largest types of snakes in the world',
            'a lot of creatures find capybaras tasty it seems, including jaguars, eagles, piranha, pumas and ocelots',
            'many countries have restrictions about hunting capybaras',
            'capybara fur turns yellowish brown on the belly and sometimes black on the face',
            'capybara front legs are slightly shorter than the hind legs',
            'capyabars can sleep in water, keeping only their noses out of the water',
            'if threatened, capybaras usual response is to flee into the water',
            'capybaras can run very fast with a top speed of about 35 km/h (22 mph)',
            'capybaras share some common features with mice, squirrels, and porcupines',
            'seventy-five percent of a capybara’s diet is only three to six plant species',
            'an adult capybara can eat 2.7 to 3.6 kilograms (6 to 8 pounds) of grass per day',
            'a capybara group maintains and defends a territory that encompasses feeding and wallowing sites',
            'among male capybaras, there is a strict dominance hierarchy enforced by chasing and, rarely, fights',
            'capybara mating season is year round with peak at beginning of wet season',
            'capybaras mate only in water, and if a female does not want to mate with a certain male, she either submerges or leaves the water',
            'dominant capybara males are highly protective of the females, but they usually cannot prevent some of the subordinates from copulating',
            'capybara pups are weaned at about 3 months old, during which time they suckle both from their own mother and the other females in the group, who are usually closely related',
            'capybaras are so trainable that in Suriname a blind man once used a capybara as a guide animal',
            'capybaras are occasionally kept as pets in the United States',
            'in Japan, following the lead of Izu Shaboten Park in 1982, multiple establishments in Japan that raise capybaras have adopted the practice of having them relax in onsen during the winter',
            'the image of a capybara features on the 2-peso coin of Uruguay',
            'fossils of the extinct Pinckney’s capybara have been found in San Diego County’s Oceanside',
            'capybaras have an extremely efficient digestive system that sustains the animal while 75% of its diet encompasses only 3 – 6 species of plants',
            'during midday, as temperatures increase, Capybaras wallow in water to keep cool and then graze in late afternoons and early evenings',
            'capybaras sleep very little, usually napping throughout the day and grazing into and through the night',
            'capybaras reach sexual maturity within 18 months and breed when conditions are right, which can be once per year (in Brazil) or throughout the year (in Venezuela and Colombia)',
            'capybaras are gentle and will usually allow humans to pet and hand-feed them',
            'capybaras look a little like overgrown guinea pigs, which is no surprise: the animals are closely related',
            'capybaras have big, barrel-shaped bodies with rather square heads',
            'capybaras are rodents and around 40% of all mammals are rodents',
            'capybaras have even been spotted in Florida',
            'Native American Guarani Indians call capybaras “master of the grasses” because they like living in lush, green spaces',
            'rainforests are perfect for capybaras because they provide an ideal habitat of long grass and water',
            'capybaras are found in every South American country apart from Chile',
            'newborn capybaras are up and about after just three or four days—ready to join the group',
            'baby capybaras cant swim',
            'should they feel as though a threat is present, capybaras can also convert to completely nocturnal behavior in which they eat and socialize entirely at night',
            'after living among marshes and swamps, Capybaras have evolved to thrive in aquatic environments',
            'capybara skin needs to be kept constantly moist and their daily diet consists primarily of aquatic plants',
            'capybara may not seem like the most agile animal on the planet, but in the water they possess a striking mobility',
            'capybaras are picky eaters',
            'for most of their lives, capybaras occupy a general “home range” from five to 500 acres',
            'capybaras are also big time cuddlers, frequently touching and grooming one another',
            'the capybara is a heavy, stocky-looking animal with a short head and muzzle in comparison to its body and hardly any tail at all',
            'they have short but sturdy limbs and hoof-like claws on their toes which along with the webbing, helps the Capybara both when negotiating the slippery banks and with swimming and also prevents the Capybara from sinking too deeply into the surrounding mud',
            'capybara`s most distinctive features is the fact that their eyes, ears and nostrils are all positioned on top of its head meaning that they still have excellent sight, sound and smell whilst in the water',
            'capybara`s coming for a soak at onsens has become something of a tradition in Japan over the past 30 years or so',
            'capybara`s front teeth never stop growing',
            'a capybara population may be established in the Santa Fe River drainage in north-central Florida',
            'a capybara has also been documented in Mississippi'
          ]),
          media_ids: new Array(data.media_id_string)
        },
          function(err, data, response) {
            if (err){
              console.log('ERROR:');
              console.log(err);
            }
            else{
              console.log('Posted an image!');
            }
          }
        );
      }
    });
  })
}


fs.readdir(__dirname + '/images', function(err, files) {
  if (err){
    console.log(err);
  }
  else{
    var images = [];
    files.forEach(function(f) {
      images.push(f);
    });
    upload_random_image(images);
  }
});


/* will delete image from folder after posting

fs.unlink(image_path, function(err){
  if (err){
    console.log('ERROR: unable to delete image ' + image_path);
  }
  else{
    console.log('image ' + image_path + ' was deleted');
  }
});
*/
